### ISSUE TITLE
[FEATURE] Nvim - add a cool neovide config

### ISSUE THREAD

**Issue by Zetsumeii** [Curs3W4ll/Dotfiles#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Why?

Neovide is a great tool when it comes to aesthetics.

### What?

Make a cool neovide config with like shark on your mouse cursor

### Additional Information

you can use :x instead of :wq

**Comment by Curs3W4ll** [comment]
This plugin does not seem to bring anything new (useful), and it is not written in lua :/

`x` command is a vim built-in
